version: 1.0.{build}
os: Visual Studio 2015
clone_folder: C:\projects\specfunc
test: off

environment:
  matrix:
    - VS_GEN: Visual Studio 10 2010
    - VS_GEN: Visual Studio 14 2015
build_script:
  - cmake -LAH -G "%VS_GEN%" -DCMAKE_INSTALL_PREFIX="%CD:\=/%/install" .
  - cmake --build . --config Release --target install
  - ctest -C Release --output-on-failure
